#!/bin/bash
# Quick Start Guide for Chartlink

echo "================================"
echo "Chartlink - Quick Start"
echo "================================"
echo ""

echo "Step 1: Setup Database (5 minutes)"
echo "1. Go to https://neon.tech"
echo "2. Sign up with GitHub"
echo "3. Create new project: 'chartlink'"
echo "4. Copy connection string"
echo "5. Paste in backend/.env as DATABASE_URL"
echo ""

echo "Step 2: Deploy Backend to Render (10 minutes)"
echo "1. cd backend"
echo "2. git init && git add . && git commit -m 'init'"
echo "3. Push to GitHub"
echo "4. Go to https://render.com"
echo "5. Create Web Service from GitHub repo"
echo "6. Add DATABASE_URL environment variable"
echo "7. Deploy"
echo "8. Copy API URL from Render"
echo ""

echo "Step 3: Deploy Frontend to Vercel (5 minutes)"
echo "1. cd frontend"
echo "2. Update .env.local with API_URL from Render"
echo "3. git init && git add . && git commit -m 'init'"
echo "4. Push to GitHub"
echo "5. Go to https://vercel.com"
echo "6. Import GitHub repo"
echo "7. Add NEXT_PUBLIC_API_URL environment variable"
echo "8. Deploy"
echo ""

echo "Step 4: Run Selenium Locally"
echo "1. Download ChromeDriver: https://chromedriver.chromium.org/"
echo "2. cd selenium"
echo "3. pip install -r requirements.txt"
echo "4. Update API_URL in scraper.py with your Render URL"
echo "5. python scraper.py"
echo ""

echo "Step 5: Monitor"
echo "1. Open https://chartlink-frontend.vercel.app (your URL)"
echo "2. Dashboard refreshes every 5 minutes"
echo "3. Data updates every 1 minute from scraper"
echo ""

echo "================================"
echo "Complete Implementation Checklist"
echo "================================"
echo "[ ] Database created on Neon"
echo "[ ] Backend deployed to Render"
echo "[ ] Frontend deployed to Vercel"
echo "[ ] Selenium scraper running locally"
echo "[ ] Dashboard shows data"
echo ""

echo "Troubleshooting:"
echo "- Backend won't start? Check DATABASE_URL format"
echo "- Frontend shows 'no data'? Check API_URL is correct"
echo "- Scraper not working? Verify ChromeDriver path"
echo ""
